kind = "web"
previewPath = "/"
title = "Maithili Store"
version = "1.0.0"
id = "artifacts/maithili-store"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 18475

[services.development]
run = "pnpm --filter @workspace/maithili-store run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/maithili-store", "run", "build" ]
publicDir = "artifacts/maithili-store/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "18475"
BASE_PATH = "/"
